### ISSUE TITLE
discount cost

### ISSUE THREAD

**Issue by sadirovizzatillo** [kozimov786/ecommerse#2]
![image](https://user-images.githubusercontent.com/65859982/120273110-80cb0000-c2c7-11eb-99e3-9e6104660d8c.png)
there is no discount cost used in some cards
![image](https://user-images.githubusercontent.com/65859982/120273201-9e986500-c2c7-11eb-8d86-8c1b96f06bf8.png)

**Comment by kozimov786** [comment]
i will add now
